### ISSUE TITLE
程序的测试入口在哪里

### ISSUE THREAD

**Issue by as7212325** [blovemaple/java-baidupcs#2]
我找了半天也没有找到提供调试的测试入口 是不是没有

**Comment by blovemaple** [comment]
blove.baidupcs.service、blove.baidupcs.api、blove.baidupcs.fs都是依赖库，可以做二次开发，本身不提供可执行的测试程序。

blove.baidupcs.script是可执行的，执行blove.baidupcs.script.BaiduPcsScriptRunner的main方法，参数传入一个properties配置文件的路径即可。配置文件内需要包含以下三个配置项（百度提供）：
app_name、api_key、secret_key

提醒一下，全部功能都需要先在百度申请PCS API权限才能用，但百度从2014年开始就关闭申请PCS API了。在那时候之前申请的目前看起来还可以用。
